# docker-compose.yml (Version pour serveur dev/prod)
# docker-compose.yml (Version paramétrable pour serveur unique)

services:
  api:
    image: ghcr.io/tounatech/arstylePanelBackend:${IMAGE_TAG:-latest}
    container_name: nest_api_${APP_ENV} # Utilise APP_ENV du .env
    ports:
      - ${API_PORT}:3000 # Utilise API_PORT du .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      # Nom de réseau basé sur APP_ENV
      - api_network_${APP_ENV}
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_${APP_ENV}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432 # Utilise POSTGRES_PORT du .env
    volumes:
      # Nom de volume basé sur APP_ENV
      - postgres_data_${APP_ENV}:/var/lib/postgresql/data
    networks:
      - api_network_${APP_ENV}
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    container_name: pgadmin4_${APP_ENV}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80 # Utilise PGADMIN_PORT du .env
    volumes:
      # Nom de volume basé sur APP_ENV
      - pgadmin_data_${APP_ENV}:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - api_network_${APP_ENV}

# Définit les réseaux (les noms seront préfixés par le nom du projet compose)
networks:
  api_network_${APP_ENV}:
    driver: bridge

# Définit les volumes (Docker créera postgres_data_dev, postgres_data_prod, etc.)
volumes:
  postgres_data_${APP_ENV}:
  pgadmin_data_${APP_ENV}:
