# docker-compose.yml
# version: '3.8' # Obsolète

services:
  api:
    container_name: nest_api_${APP_ENV:-prod}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT:-3000}:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_network
    # Commande pour démarrer l'application - CORRIGÉE
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_${APP_ENV:-prod}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    container_name: pgadmin4_${APP_ENV:-prod}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT:-5050}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
