# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB = dbPgArPanel 
ENV POSTGRES_USER = pgArPanelAdmin
ENV POSTGRES_PASSWORD = L8RsWF9u~eTxVE+b

# Expose the PostgreSQL port
EXPOSE 5432